### ISSUE TITLE
Изпит?

### ISSUE THREAD

**Issue by luchob** [dddobrev/Auto-WorkShop-Pro#1]
Миткооо? Мина ли изпитът? Надявам се, нямало е драми...

Поздрави,
Л.

**Comment by dddobrev** [comment]
Добър вечер Лъчооооо :)))))
Изпита мина. Благодарение на теб и твоите съвети имам 5.66! Огромна радост за мен!  Нямах време  да напиша всички тестове, но направих различни за да покажа знания. Оценката за мен не е толкова важна. По-важно е, че научих много неща и се развивам. За мен ще е интересно, какво са казали твоите колеги за идеята, която защитих. 
Изказвам своите хиляди Благодарности, на това което ни научи и показа! Много си голям, така да знаеш!
Започнах да уча Java на шега, а се оказа любов от пръв поглед. Това, което започнах да пиша се хареса на мои колеги с автосервизи. Един ден това може да е платформа, която се ползва от много професионалисти (за сервизите им) и хора, които искат да си водят отчетност за МПС-тата. Като се напълни с данни,  се надявам да се правят справки и за най-често срещаните дефекти при различните модели коли, мотори и т.н.  :) Имам много идеи за разрастването проекта,  но ... да сме живи и здрави :) Четене и писане му е майката. Започнах да разглеждам Angular.
Ще се радвам много да се видим лятото. Касата бира от мен те чака :) Живея в малко градче на северното черноморе, Шабла. При нас е много спокойно. Плажа при е ... километри пясък. Имаме си страхотен  бар на пясъка и ... :) 
Имам фейсбук профил https://www.facebook.com/dddobrev/  тел номер на който може да ме намериш е 0888429635!

Гордея се, че съм бил твой ученик! Още веднъж едно Огромно БЛАГОДАРЯ!
Ще съм много щастлив, ако се видим :) 

Поздрави,
Митко
